# DATABASE
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dateanu?serverTimezone=UTC&characterEncoding=UTF-8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: springuser
    password: 1234

  jpa:
    properties:
      hibernate:
        # INIT
        ddl-auto: create # Only 'create' when init
        # DEV
        # ddl-auto: update # Only 'create' when init
        show_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true

  messages:
    basename: messages,errors

  fallback-to-system-locale: false

# SPRINGDOC
springdoc:
  packages-to-scan: com.example.dateanu.rest_api
  default-consumes-media-type: application/json;charset:UTF-8
  swagger-ui.path: /swagger
  swagger-ui.disable-swagger-default-url: true
  swagger-ui.display-request-duration: true
  swagger-ui.operations-sorter: alpha

# ACTUATOR
#management:
#  endpoints:
#    web:
#      exposure:
#        include: *

# SECURITY
#spring.security.user.name:jihoon
#spring.security.user.password:thtsme
#logging.level.org.springframework.boot.autoconfigure.security:INFO
org:
  springframework:
    boot:
      autoconfigure:
        security: INFO

# PORT
server:
  port: 9090
